# Generated by Django 3.2.6 on 2021-11-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_mbti'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poster_number',
            field=models.IntegerField(default=0),
        ),
    ]
