# Generated by Django 3.2.6 on 2021-11-18 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_path', models.TextField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('actors', models.ManyToManyField(blank=True, related_name='movies', to='movies.Actor')),
                ('genres', models.ManyToManyField(to='movies.Genre')),
                ('pick_users', models.ManyToManyField(blank=True, related_name='picked_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
